apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-service
  namespace: snmp-app
spec:
  selector:
    app: snmp-trap-sender
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  # adjust to your app's listening port if needed
  type: ClusterIP
